# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menteeapplication',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='menteeapplication',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_occupation',
            field=models.CharField(blank=True, max_length=64, verbose_name='Current Occupation?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expectations',
            field=models.TextField(blank=True, verbose_name='Tell us about your expectations?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.DeleteModel(
            name='MenteeApplication',
        ),
        migrations.DeleteModel(
            name='MentorApplication',
        ),
    ]
