# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-23 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('tech', 'Tech'), ('arts', 'Arts'), ('programming', 'Programming'), ('web_development', 'Web Development'), ('actor', 'Actor'), ('actress', 'Actress'), ('law', 'Law'), ('medicine', 'Medicine')], default='', max_length=255),
        ),
    ]
