# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-16 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_of_study', models.CharField(
                    choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('certificate', 'Certificate'),
                             ('diploma', 'Diploma'), ('undergraduate', 'Undergraduate'),
                             ('postgraduate', 'Postgraduate')], max_length=255)),
                ('institution_name', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(max_length=255)),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Education_background',
                'verbose_name_plural': 'Education_background',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='MentorshipArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentorship_areas', multiselectfield.db.fields.MultiSelectField(
                    choices=[('academic_assistance', 'Academic Assistance'),
                             ('entrepreneurship', 'Entrepreneurship (Having difficulties being your own boss?)'),
                             ('career_counceling', 'Career Counceling'),
                             ('career_readiness', 'Career readiness (Interviews or Job hunting)'),
                             ('grief_loss', 'Coping with grief and loss'), ('addictions', 'Coping with addictions'),
                             ('abuse', 'Trauma and Abuse'), ('no_preference', 'Prefere not to answer')], default='',
                    max_length=113)),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentorship Area',
                'verbose_name_plural': 'Mentorship Areas',
            },
        ),
    ]
