# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-29 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestMentorship',
            new_name='Mentorship',
        ),
    ]
