# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-14 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_previously_logged_in',
            field=models.CharField(default=False, max_length=5),
        ),
    ]
