# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-31 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170531_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menteeprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentee')], default='mentee', max_length=6),
        ),
        migrations.DeleteModel(
            name='MenteeProfile',
        ),
        migrations.DeleteModel(
            name='MentorProfile',
        ),
    ]
