# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-05 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20170531_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenteeProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.Profile')),
                ('expectations', models.TextField()),
            ],
            bases=('authentication.profile',),
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.Profile')),
                ('occupation', models.CharField(max_length=255)),
            ],
            bases=('authentication.profile',),
        ),
    ]
