# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-14 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0003_auto_20170714_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(
                choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('certificate', 'Certificate'),
                         ('diploma', 'Diploma'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate')],
                default='secondary', max_length=50),
        ),
    ]
