# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-14 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0006_profile_mentorship_areas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='interest',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='interest',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
