# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-12 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_profile_mentorship_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='highest_level_of_study',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate')], default='', max_length=255),
        ),
    ]
