# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-24 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0016_auto_20170921_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profiles/default.jpg', upload_to='profiles/'),
        ),
    ]
