# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-23 10:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0017_auto_20170924_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='mentorship_areas',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('academic_assistance', 'Academic Assistance'), (
                'entrepreneurship', 'Entrepreneurship (Having difficulties being your own boss?)'),
                                                                       ('career_counseling', 'Career Counseling'), (
                                                                           'career_readiness',
                                                                           'Career readiness (Interviews or Job hunting)'),
                                                                       ('grief_loss', 'Coping with grief and loss'),
                                                                       ('addictions', 'Coping with addictions'),
                                                                       ('abuse', 'Trauma and Abuse'),
                                                                       ('no_preference', 'Prefer not to answer')],
                                                              default='', max_length=113),
        ),
    ]
