# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-20 20:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0019_connection_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.BooleanField(default=False)),
                ('entrepreneurship', models.BooleanField(default=False)),
                ('career_counseling', models.BooleanField(default=False)),
                ('career_readiness', models.BooleanField(db_column='c/c++', default=False, verbose_name='c++')),
                ('addictions', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interests',
            },
        ),
        migrations.RemoveField(
            model_name='language',
            name='user',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
