# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-10 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_auto_20171129_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
