# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-13 17:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestone', to=settings.AUTH_USER_MODEL),
        ),
    ]
