# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-17 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('milestone', '0002_auto_20171213_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='to_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
