# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-17 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('milestone', '0003_milestone_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='to_user',
        ),
    ]
